"use client"

import { useUIStore } from "@/stores/ui-store"
import { X, Sparkles, Share2, Copy, Edit3, Maximize2, CheckCircle2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"

export function CanvasPanel() {
  const { isCanvasOpen, closeCanvas } = useUIStore()

  if (!isCanvasOpen) return null

  return (
    <div className="w-full h-full flex flex-col bg-white dark:bg-[#1a1d21] border-l animate-in slide-in-from-right duration-500 ease-out shadow-2xl">
      {/* Canvas Header */}
      <header className="h-14 px-6 flex items-center justify-between border-b shrink-0 bg-slate-50 dark:bg-muted/20">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded bg-blue-600 flex items-center justify-center shadow-lg shadow-blue-600/20">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <div>
            <h3 className="font-black text-sm tracking-tight">AI Canvas</h3>
            <div className="flex items-center gap-2">
              <span className="text-[10px] text-muted-foreground font-bold uppercase tracking-widest">Draft v1.2</span>
              <Badge variant="outline" className="h-4 text-[9px] px-1 bg-green-500/10 text-green-600 border-green-200">Live</Badge>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="sm" className="h-8 text-xs font-bold px-2">
            <Share2 className="w-3.5 h-3.5 mr-1.5" /> Share
          </Button>
          <Separator orientation="vertical" className="h-4 mx-1" />
          <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full" onClick={closeCanvas}>
            <X className="w-4 h-4" />
          </Button>
        </div>
      </header>

      <ScrollArea className="flex-1">
        <div className="max-w-3xl mx-auto px-8 py-12 flex flex-col gap-8">
          {/* Document Content */}
          <div className="flex flex-col gap-4">
            <h1 className="text-4xl font-black tracking-tighter leading-none">Relay Agent Workspace Launch Roadmap</h1>
            <div className="flex items-center gap-4 text-sm text-muted-foreground font-medium">
              <div className="flex items-center gap-1.5">
                <div className="w-5 h-5 rounded-full bg-purple-100 flex items-center justify-center">
                  <Sparkles className="w-3 h-3 text-purple-600" />
                </div>
                Generated by AI
              </div>
              <span>•</span>
              <span>Updated 2 mins ago</span>
            </div>
          </div>

          <div className="prose dark:prose-invert max-w-none">
            <p className="text-lg text-muted-foreground leading-relaxed">
              This document outlines the strategic steps for the alpha release of Relay Agent Workspace. 
              Focus is on ensuring the AI-native features feel seamless and intuitive for Slack power users.
            </p>

            <div className="grid grid-cols-1 gap-4 my-8">
              <TaskItem title="Core Layout Implementation" completed />
              <TaskItem title="Simulated Streaming API" completed />
              <TaskItem title="AI Canvas & Artifacts Panel" current />
              <TaskItem title="User Collaboration Insights" />
            </div>

            <h2 className="text-2xl font-black mt-8 mb-4 tracking-tight">Key Architectural Decisions</h2>
            <div className="bg-muted/30 border rounded-xl p-6 font-mono text-xs leading-relaxed overflow-x-auto">
              {`// Modular UI Architecture
export const WorkspaceLayout = ({ children }) => {
  const { isCanvasOpen } = useUIStore();
  return (
    <div className="flex h-screen overflow-hidden">
      <PrimaryNav />
      <div className="flex-1 flex overflow-hidden">
        <ChannelSidebar />
        <MainContent width={isCanvasOpen ? '60%' : '100%'}>
          {children}
        </MainContent>
        {isCanvasOpen && <CanvasPanel width="40%" />}
      </div>
    </div>
  );
};`}
            </div>
          </div>
        </div>
      </ScrollArea>

      {/* Canvas Footer */}
      <footer className="p-4 border-t bg-slate-50/50 dark:bg-muted/10">
        <div className="flex items-center justify-between gap-4 max-w-3xl mx-auto">
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="h-8 font-bold text-xs">
              <Edit3 className="w-3.5 h-3.5 mr-1.5" /> Edit document
            </Button>
            <Button variant="outline" size="sm" className="h-8 font-bold text-xs">
              <Copy className="w-3.5 h-3.5 mr-1.5" /> Copy code
            </Button>
          </div>
          <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground">
            <Maximize2 className="w-4 h-4" />
          </Button>
        </div>
      </footer>
    </div>
  )
}

function TaskItem({ title, completed, current }: { title: string, completed?: boolean, current?: boolean }) {
  return (
    <div className={cn(
      "flex items-center gap-3 p-3 rounded-lg border transition-all",
      completed ? "bg-green-50/50 border-green-100 dark:bg-green-500/5 dark:border-green-900/20" : 
      current ? "bg-blue-50 border-blue-200 dark:bg-blue-500/10 dark:border-blue-800 ring-1 ring-blue-500/20" : "bg-white dark:bg-[#1a1d21] border-border"
    )}>
      {completed ? (
        <CheckCircle2 className="w-5 h-5 text-green-500 shrink-0" />
      ) : (
        <div className={cn("w-5 h-5 rounded-full border-2 shrink-0", current ? "border-blue-500" : "border-muted")} />
      )}
      <span className={cn("text-sm font-bold", completed ? "text-green-700 dark:text-green-400 line-through opacity-50" : "text-foreground")}>
        {title}
      </span>
      {current && (
        <Badge className="ml-auto bg-blue-500 text-[9px] uppercase font-black px-1.5 h-4">In Progress</Badge>
      )}
    </div>
  )
}
